name: Isomerc's Arcanaeum
description: >
  Isomerc's Arcanaeum
about: >
  The blog and website of Isomerc, a long time EVE Online player and tribe leader. I write about EVE Online, programming, political philosophy, economics, and geopolitics within the sandbox.

master_repo: false
url: "http://isomerc.com"
markdown: kramdown
highlighter: rouge

plugins: ["jekyll-paginate", "jekyll-gist", "jekyll-feed"]

paginate: 4

logo: logo.png
disqus_shortname:

rtl: false
owner:
  name: Isomerc
  avatar: "https://avatars.githubusercontent.com/u/181777279?v=4"
  email: "eve.isomerc@protonmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: isomerc
  github: https://github.com/isomerc

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
